#include<stdio.h>
#include<conio.h>
void main()
{
int a,b,c;
clrscr();
printf("enter values:");
scanf("%d,%d,%d",&a,&b,&c);
if(a>b,a>c)
{
 printf("a is big");
}
else
{
 printf("b, is big");
 printf("c is big");

}
 if(b>a,b>c)
{
 printf("b is big");
 }
 else
 {
 printf("a is big");
 printf("c is big");
}
  if(c>a,c>b)
 {
 printf("c is big");
 }
 else
{
 printf("a is big");
printf("b is big");
}
getch();
}
